server:
  port: 9100

spring:
  application:
    name: admin-service
  cloud:
    nacos:
#      config:
#        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/phoenix?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B0&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+0
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: maxwell_source
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

grpc:
  server:
    port: 9090
  client:
    admin-service:
      host:
        - 127.0.0.1
      port:
        - 9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT


mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

maxwell:
  group-id: maxwell_source
  topics:
    task_config: maxwell_maxwell_source_task_config