spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/phoenix?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B0&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+0

mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/*.xml