package com.vova.phoenix.dao;

import com.vova.phoenix.model.repository.AdminUserNode;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Service;

import java.util.List;

@Mapper
@Service
public interface AdminUserNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_node
     *
     * @mbg.generated
     */
    int insert(AdminUserNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_node
     *
     * @mbg.generated
     */
    List<AdminUserNode> selectAll();
}